<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ubah</name>
   <tag></tag>
   <elementGuidId>5aeaff60-9a91-4b69-9056-26f3e6e327f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-list-30-menuitem-27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'ubah')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bdfe2604-805f-4049-8e68-faba3213ff9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-list-30-menuitem-27</value>
      <webElementGuid>28faea6d-9dea-4dfc-b3ad-a0f2455d507e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>3bc1aa67-d3e8-40c7-96fd-64aef3063f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8859276b-860d-40df-b723-b06a98e06e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-menu__menuitem css-13c7rae</value>
      <webElementGuid>ac2f3fcf-71a2-4e47-8239-517c7319280c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categories/2f2fd9bb-2871-44bb-a1a7-d40e9685082c/edit</value>
      <webElementGuid>1f78773d-c6b4-4b18-8c96-f644b36b012a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad4cded8-6cfa-439a-9b40-87ae25d421be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ubah</value>
      <webElementGuid>d44f9978-754c-4f14-b3ea-68c8c2a349fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-list-30-menuitem-27&quot;)</value>
      <webElementGuid>55f77667-6298-45b1-8577-834541ab1e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu-list-30-menuitem-27']</value>
      <webElementGuid>37b11d14-ab2e-4440-bd1e-d6d71ad512dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-list-30']/a</value>
      <webElementGuid>d37211f0-77ef-4556-8110-612da0f6719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'ubah')]</value>
      <webElementGuid>1bfefee4-b365-4971-a99c-6758d6d1e139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ini adalah kategori khusus'])[1]/following::a[1]</value>
      <webElementGuid>42caacf3-4d5a-42ae-a7cf-7ff1c7a08c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khusus'])[1]/following::a[1]</value>
      <webElementGuid>8c533e1f-2f22-48c8-a1ba-cb504ff53f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hapus'])[1]/preceding::a[1]</value>
      <webElementGuid>0e7a39f2-fd57-40aa-8e39-4da6b97311cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Umum'])[1]/preceding::a[1]</value>
      <webElementGuid>c033faea-8eaf-409c-addd-65b51bfaa433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ubah']/parent::*</value>
      <webElementGuid>2bfaca42-3a11-4400-ad2c-10d21fe0bbe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/categories/2f2fd9bb-2871-44bb-a1a7-d40e9685082c/edit')]</value>
      <webElementGuid>7bf7c075-b26d-4244-aa36-09a0fd3ab156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/a</value>
      <webElementGuid>c7a6f777-1414-4b92-b989-40754c91ddcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'menu-list-30-menuitem-27' and @href = '/categories/2f2fd9bb-2871-44bb-a1a7-d40e9685082c/edit' and (text() = 'ubah' or . = 'ubah')]</value>
      <webElementGuid>3122fff9-9bfb-474d-a833-f85dce7329a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
